seed: 0
output_dir: './output' # path to save checkpoint/strategy
load_checkpoint: ''
src_strategy_path_or_dir: ''
auto_trans_ckpt: False  # If true, auto transform load_checkpoint to load in distributed pipeline
only_save_strategy: False
resume_training: False
use_parallel: True
run_mode: 'train'

# trainer config
trainer:
  type: CausalLanguageModelingTrainer
  model_name: 'deepseekV3'

# runner config
runner_config:
  epochs: 2
  batch_size: 1
  sink_mode: True
  sink_size: 1

# optimizer
optimizer:
  type: AdamW
  betas: [0.9, 0.95]
  eps: 1.e-8
  learning_rate: 0 #3.e-4

# lr schedule
lr_schedule:
  type: CosineWithWarmUpLR
  learning_rate: 2.e-5
  lr_end: 2.e-5
  warmup_ratio: 0.0
  total_steps: -1 # -1 means it will load the total steps of the dataset

# dataset
train_dataset: &train_dataset
  data_loader:
    type: MindDataset
    dataset_dir: "/data/x00669956/code_xfc/data8k"
    shuffle: False
  input_columns: ["input_ids"]  # "input_ids" , labels are used in instruction finetune.
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: True
  repeat: 1
  numa_enable: False
  prefetch_size: 1
train_dataset_task:
  type: CausalLanguageModelDataset
  dataset_config: *train_dataset
# if True, do evaluate during the training process. if false, do nothing.
# note that the task trainer should support _evaluate_in_training function.
do_eval: False
eval_step_interval: -1        # num of step intervals between each eval, -1 means no step end eval.
eval_epoch_interval: 50        # num of epoch intervals between each eval, 1 means eval on every epoch end.

# eval dataset
eval_dataset: &eval_dataset
  data_loader:
    type: MindDataset
    dataset_dir: ""
    shuffle: False
  input_columns: ["input_ids"]
  num_parallel_workers: 8
  python_multiprocessing: False
  drop_remainder: False
  repeat: 1
  numa_enable: False
  prefetch_size: 1
eval_dataset_task:
  type: CausalLanguageModelDataset
  dataset_config: *eval_dataset

# mindspore context init config
context:
  mode: 0 #0--Graph Mode; 1--Pynative Mode
  device_target: "Ascend"
  max_call_depth: 10000
  max_device_memory: "56GB"
  save_graphs: False
  save_graphs_path: "./graph"
  #graph_kernel_flags: "--enable_cluster_ops=MatMul,GroupMatMul --online_tuning=1"
  ascend_config:    # add
    parallel_speed_up_json_path: "/data/x00669956/mindformers_910c/research/deepseek3/parallel_speed_up.json"    # add
  enable_interleave_parallel_branch: True
  jit_config:
    jit_level: "O1"

# parallel context config
parallel:
  parallel_mode: 1 # 0-data parallel, 1-semi-auto parallel, 2-auto parallel, 3-hybrid parallel
  gradients_mean: False
  enable_alltoall: True
  full_batch: True
  search_mode: "sharding_propagation"
  enable_parallel_optimizer: True
  strategy_ckpt_save_file: "./ckpt_strategy.ckpt"
  # pipeline_config:
  #    pipeline_interleave: True
  #    pipeline_scheduler: 'seqpipe'
  parallel_optimizer_config:
    gradient_accumulation_shard: False
    parallel_optimizer_threshold: 64
    # optimizer_weight_shard_size: 16

# default parallel of device num = 16 for Atlas 800
parallel_config:
  data_parallel: 24
  model_parallel: 8
  pipeline_stage: 4 #8
  expert_parallel: 32
  micro_batch_num: 160
  vocab_emb_dp: True
  use_seq_parallel: True
  gradient_aggregation_group: 4
# when pipeline parallel is greater than 1, we can set micro_batch_interleave_num=2, that may accelerate the train process.
micro_batch_interleave_num: 1

# recompute config
recompute_config:
  recompute: [[9, 7, 6, 8, 7, 6, 3, 0]] #[[4,4,4,4,4,4,4,4], [4,4,4,4,4,3,3,2]] #True #[[4,4,4,4,4,4,4,3],[4,3,3,3,3,3,3,3]] #True #[[4,4,4,4,4,4,4,3],[3,4,4,3,3,3,3,3]] #True #[[0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0]] #False #[8, 8, 8, 8, 7, 7, 6, 6]
  #select_recompute: ['rcast', 'feed_forward\.shared_experts', 'attention', 'ffn_norm','attention_norm', 'feed_forward\.routed_experts\.ffn\.reshape', 'feed_forward\.routed_experts\.ffn\.gate_gather'] #['attention','attention_norm', 'feed_forward\.w1','feed_forward\.w2', 'ffn_norm',] #['feed_forward\.routed_experts\.transpose_5dim_ep2','feed_forward\.routed_experts\.transpose_mp1','feed_forward\.routed_experts\.stride_slice', 'feed_forward\.routed_experts\.stride_slice_ep', 'feed_forward\.routed_experts\.stride_slice_outer_dp_mp','feed_forward\.routed_experts\.stride_slice_outer_ep_mp','feed_forward\.routed_experts\.stride_slice_allgather','\.activation\.silu', 'feed_forward\.routed_experts\.stride_slice', 'feed_forward\.routed_experts\.router\.gather',  'feed_forward\.shared_experts\.reshape', 'feed_forward\.shared_experts\.w1\.reshape', 'feed_forward\.reshape', 'feed_forward\.shared_experts\.w2\.reshape', 'feed_forward\.shared_experts\.w3\.reshape', 'feed_forward\.routed_experts\.ffn\.w1\.reshape', 'feed_forward\.routed_experts\.ffn\.w2\.reshape', 'feed_forward\.routed_experts\.ffn\.w3\.reshape', 'feed_forward\.routed_experts\.router\.dense\.reshape', 'feed_forward\.routed_experts\.router\.reshape', 'freqs_mgr\.reshape', 'reshape','attention', 'feed_forward\.w1','feed_forward\.w2', 'ffn_norm','attention_norm','lq_norm','lkv_norm', 'feed_forward\.routed_experts\.reshape'] ##False
  #'feed_forward\.shared_experts\.w1\.reshape': True
  # 'feed_forward\.shared_experts\.w2\.reshape': True
  # 'feed_forward\.reshape': True
  # 'feed_forward\.routed_experts\.ffn\.w3\.reshape' : True
  # 'feed_forward\.routed_experts\.ffn\.w1\.reshape' : True
  # 'feed_forward\.routed_experts\.ffn\.w2\.reshape' : True
  # 'feed_forward\.routed_experts\.router\.dense\.reshape' : True
  # 'feed_forward\.shared_experts\.w3\.reshape': True
  # 'freqs_mgr\.reshape': True
  # 'feed_forward\.routed_experts\.router\.reshape': True
  # 'reshape': True
  # 'attention': True
  # 'feed_forward\.w1': True
  # 'feed_forward\.w2': True
  #  'feed_forward\.w3': True
  #  'ffn_norm': True
  #  'attention_norm': True
  #  'lq_norm': True
  #  'lkv_norm': True
  parallel_optimizer_comm_recompute: False
  mp_comm_recompute: True
  recompute_slice_activation: True

  # pipeline config
model:
  model_config:
    type: DeepseekV3Config
    auto_register: deepseek3_config.DeepseekV3Config
    batch_size: 1 # add for increase predict
    pp_interleave_num: 1
    seq_length: 8192
    hidden_size: 7168
    num_layers: &num_layers 61
    num_heads: 128
    max_position_embeddings: 163840 #8192
    intermediate_size: 18432
    kv_lora_rank: 512
    n_kv_heads: 128
    q_lora_rank: 1536
    qk_rope_head_dim: 64
    v_head_dim: 128
    qk_nope_head_dim: 128
    vocab_size: 129280
    multiple_of: 256
    rms_norm_eps: 1.0e-6
    bos_token_id: 100000
    eos_token_id: 100001
    pad_token_id: 100001
    ignore_token_id: -100
    compute_dtype: "bfloat16"
    layernorm_compute_type: "float32"
    softmax_compute_type: "float32"
    rotary_dtype: "float32"
    router_dense_type: "float32"
    param_init_type: "float32"
    use_past: False
    extend_method: "None"
    use_flash_attention: True
    offset: [[2, 0, 0, 1, 1, 1, 1, 0]] #[0,0,0,1,1,2,3,-1] #[[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,0],[1,1,1,1,1,1,1,0]] #[1,1,1,1,1,1,1,-1] # [[1,1,1,1,1,1,1,1],[1,1,1,1,1,1,1,-1]] #[[1,1,1,1,1,1,1,0], [1,1,1,1,1,1,1,0]] #[[1,1,1,1,1,1,1,0], [0,1,1,1,1,1,2,0]] #[[1,1,1,1,1,1,1,1], [0,1,1,1,1,1,1,0]] #[0,0,1,1,1,1,1,0] #[1, 1, 1, 1, 1, 1, 1, -1]
    checkpoint_name_or_path: ""
    repetition_penalty: 1
    max_decode_length: 1024
    top_k: 5
    top_p: 1
    theta: 10000.0
    do_sample: False
    return_extra_loss: False
    mtp_depth: &mtp_depth 1
    mtp_loss_factor: 0.3
    use_force_expert_balance: True
  arch:
    type: DeepseekV3ForCausalLM
    auto_register: deepseek3_model.DeepseekV3ForCausalLM

#moe
moe_config:
  moe_shared_expert_overlap: True
  expert_num: &expert_num 256
  expert_group_size: 8
  capacity_factor: 1.0
  aux_loss_factor: 0.05
  num_experts_chosen: 8
  # topk_method: "group_limited_greedy"
  routing_policy: "TopkRouterV2"
  enable_sdrop: False
  balance_via_topk_bias: &balance_via_topk_bias True
  topk_bias_update_rate: &topk_bias_update_rate 0.0001
  use_fused_ops_topkrouter: True
  group_wise_a2a: False
  shared_expert_num: 1
  routed_scaling_factor: 2.5
  norm_topk_prob: True #pta是True
  first_k_dense_replace: 3
  moe_intermediate_size: 2048
  # greedy_group_limited strategy, select topk_group from n_group
  topk_group: 4
  n_group: 8
  aux_loss_factors: [0.001]
  aux_loss_types: ["expert"]
  z_loss_factor: 0.0
  expert_model_parallel: 1
  use_gmm: True
  use_gating_sigmoid: False
  enable_gmm_safe_tokens: False #True

processor:
  return_tensors: ms
  tokenizer:
    unk_token: '<unk>'
    bos_token: '<｜begin▁of▁sentence｜>'
    eos_token: '<｜end▁of▁sentence｜>'
    pad_token: '<｜end▁of▁sentence｜>'
    type: LlamaTokenizerFast
    vocab_file: './path/tokenizer.pipeline'
    tokenizer_file: './path/tokenizer.json'
  type: LlamaProcessor


# callbacks
callbacks:
  - type: MFLossMonitor
    #aux_loss_free_config:
    #  num_layers: *num_layers
    #  mtp_depth: *mtp_depth
    #  expert_num: *expert_num
    #  balance_via_topk_bias: *balance_via_topk_bias
    #  topk_bias_update_rate: *topk_bias_update_rate
    per_print_times: 1
  - type: ObsMonitor

# metric
metric:
  type: PerplexityMetric

# wrapper cell config
runner_wrapper:
  type: MFTrainOneStepCell
  scale_sense: 1.0
  use_clip_grad: True

eval_callbacks:
  - type: ObsMonitor

auto_tune: False
filepath_prefix: './autotune'
autotune_per_step: 10

profile: False #True
profile_start_step: 11
profile_stop_step: 12
init_start_profile: False
profile_communication: False
profile_memory: True
layer_scale: False
layer_decay: 0.65
lr_scale_factor: 256

# aicc
remote_save_url: "Please input obs url on AICC platform."

# memory usage in the 12 stages
# stage 0, nlayer=5, recom=0, Memory=38779 MB
# stage 1, nlayer=5, recom=1, Memory=56184 MB
# stage 2, nlayer=5, recom=1, Memory=54137 MB
# stage 3, nlayer=5, recom=0, Memory=56185 MB
# stage 4, nlayer=5, recom=0, Memory=54250 MB
# stage 5, nlayer=5, recom=0, Memory=52216 MB
# stage 6, nlayer=5, recom=0, Memory=49019 MB
# stage 7, nlayer=5, recom=0, Memory=46971 MB
# stage 8, nlayer=5, recom=0, Memory=44012 MB
# stage 9, nlayer=6, recom=0, Memory=50044 MB
# stage10, nlayer=6, recom=0, Memory=47100 MB
# stage11, nlayer=5, recom=0, Memory=41910 MB
